Repository Team-404-UNLaM/FoodTrack, pull requests merged in 2022-06, with the labels that each got.

#62 Camera qr/feature
  FoodTrack/app/src/main/java/com/team404/foodtrack/ui/camera/CameraFragment.kt
Labels: bug

#63 Interaction wsp/feature
  FoodTrack/app/src/main/java/com/team404/foodtrack/data/Market.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/mockServer/mocks/MarketsMocks.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/mockServer/mocks/MenuItemsMocks.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/mockServer/mocks/MenusMocks.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/mockServer/mocks/ProductsMocks.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/ui/order/SelectOrderPaymentMethodFragment.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/utils/DateAndTime.kt
Labels: enhancement

#69 Historial de pedidos
  FoodTrack/app/src/main/java/com/team404/foodtrack/MainActivity.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/configuration/module.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/data/Order.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/data/OrderHistory.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/domain/adapters/MarketAdapter.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/domain/adapters/OrderHistoryAdapter.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/domain/factories/OrdersHistoryViewModelFactory.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/domain/holders/OrderHistoryViewHolder.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/domain/mappers/OrderHistoryMapper.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/domain/repositories/OrderHistoryRepository.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/domain/services/OrdersHistoryService.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/mockServer/MockServer.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/mockServer/mocks/MarketsMocks.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/mockServer/mocks/OrdersHistoryMocks.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/ui/gallery/GalleryFragment.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/ui/gallery/GalleryViewModel.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/ui/history/OrdersHistoryFragment.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/ui/history/OrdersHistoryViewModel.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/ui/home/HomeFragment.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/ui/home/HomeViewModel.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/ui/market/MarketListFragment.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/ui/order/SelectPaymentMethodFragment.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/ui/slideshow/SlideshowFragment.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/ui/slideshow/SlideshowViewModel.kt
  FoodTrack/app/src/main/res/drawable/ic_black_market.xml
  FoodTrack/app/src/main/res/drawable/ic_history.xml
  FoodTrack/app/src/main/res/layout/fragment_orders_history.xml
  FoodTrack/app/src/main/res/layout/grid_layout_order_history.xml
  FoodTrack/app/src/main/res/menu/activity_main_drawer.xml
  FoodTrack/app/src/main/res/navigation/mobile_navigation.xml
  FoodTrack/app/src/main/res/values/strings.xml
Labels: enhancement

#78 Maps click listeners
  FoodTrack/app/src/main/java/com/team404/foodtrack/ui/maps/MapsFragment.kt
  FoodTrack/app/src/main/res/layout/item_market_map.xml
  FoodTrack/app/src/main/res/navigation/mobile_navigation.xml
Labels: enhancement

#77 Jetpack compose implementation in fav markets screen
  FoodTrack/app/build.gradle
  FoodTrack/app/src/main/java/com/team404/foodtrack/MainActivity.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/domain/factories/FavsMarketsViewModelFactory.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/ui/market/favs/FavFragment.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/ui/market/favs/FavsViewModel.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/ui/market/favs/ui/theme/Color.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/ui/market/favs/ui/theme/Shape.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/ui/market/favs/ui/theme/Theme.kt
  FoodTrack/app/src/main/java/com/team404/foodtrack/ui/market/favs/ui/theme/Type.kt
  FoodTrack/app/src/main/res/drawable/food_image.png
  FoodTrack/app/src/main/res/drawable/ic_favorite.xml
  FoodTrack/app/src/main/res/layout/fragment_fav.xml
  FoodTrack/app/src/main/res/menu/activity_main_drawer.xml
  FoodTrack/app/src/main/res/navigation/mobile_navigation.xml
  FoodTrack/app/src/main/res/values/strings.xml
  FoodTrack/build.gradle
  FoodTrack/gradle/wrapper/gradle-wrapper.properties
Labels: enhancement, design
